# For more information: https://laravel.com/docs/sail
version: '3'

networks:
    lumen:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - '80:80'
        volumes:
            - ./lumen:/var/www
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - lumen
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: lumen
        volumes:
            - ./lumen:/var/www
        ports:
            - '9001:9000'
        networks:
            - lumen
